// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/10/2024, 11:05:07 AM
const configMerger = require("C:/Users/user/UP/Practice/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/user/UP/Practice/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/plugins/**/*.{js,ts,mjs}","C:/Users/user/UP/Practice/composables/**/*.{js,ts,mjs}","C:/Users/user/UP/Practice/utils/**/*.{js,ts,mjs}","C:/Users/user/UP/Practice/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/UP/Practice/app.config.{js,ts,mjs}"] } }));

module.exports = config
